server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JAVA15_POSTGRE_URL}
    username: ${JAVA15_POSTGRE_USERNAME}
    password: ${JAVA15_POSTGRE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    name: proje.log
  level:
    root: info
    com.mcann.java15_x: trace
  logback:
    rollingpolicy:
      max-file-size: 2MB


java15:
  jwt:
    secret-key: ${JAVA15_JWT_SECRETKEY}
    issuer: ${JAVA15_JWT_ISSUER}